---
driver:
  name: vagrant
  ssh:
    insert_key: false
  synced_folders:
    - ["/tmp/opscode-analytics", "/etc/opscode-analytics"]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: centos-6.6

suites:
- name: standalone
  run_list:
  - recipe[test::hostsfile]
  - recipe[chef-server]
  - recipe[chef-server::add_ons]
  - recipe[test::default_user_and_org]
  driver:
    vm_hostname: chef.example.com
    network:
      - ['private_network', {ip: '33.33.33.10'}]
  attributes:
    chef-server:
      api_fqdn: 'chef.example.com'
      analytics:
        fqdn: 'analytics.example.com'
      add_ons:
        - opscode-manage
        - opscode-reporting
        - opscode-push-jobs-server
      configuration:
        oc_id:
          applications:
            analytics:
              redirect_uri: 'https://analytics.example.com/'
        rabbitmq:
          vip: '33.33.33.10'
          node_ip_address: '0.0.0.0'

- name: analytics
  run_list:
  - recipe[test::hostsfile]
  - recipe[chef-server::analytics]
  driver:
    vm_hostname: analytics.example.com
    network:
      - ['private_network', {ip: '33.33.33.11'}]
  attributes:
    chef-server:
      api_fqdn: 'chef.example.com'
      analytics:
        fqdn: 'analytics.example.com'